Repository cse-uprc/acm-app-microservice, pull requests merged in 2020-08, with the labels that each got.

#59 Acmapp 54 create user request
  CHANGELOG.md
  src/main/java/com/acm/app/user/client/UserClient.java
  src/main/java/com/acm/app/user/client/domain/request/UserGetRequest.java
  src/main/java/com/acm/app/user/dao/UserDAO.java
  src/main/java/com/acm/app/user/mapper/UserMapper.java
  src/main/java/com/acm/app/user/rest/UserController.java
  src/main/java/com/acm/app/user/service/UserService.java
  src/main/resources/version.properties
  src/test/java/com/acm/app/user/client/UserClientTest.java
  src/test/java/com/acm/app/user/service/UserServiceTest.java
Labels: feature

#62 Acmapp 14 create authentication controller
  CHANGELOG.md
  src/main/java/com/acm/jwt/auth/controller/AuthorizationController.java
  src/main/java/com/acm/jwt/auth/service/AuthorizationService.java
  src/main/java/com/acm/jwt/model/JwtRequest.java
  src/main/java/com/acm/jwt/model/JwtResponse.java
Labels: feature

#74 Acmapp 71 create user exceptions
  CHANGELOG.md
  src/main/java/com/acm/app/user/client/UserClient.java
  src/main/java/com/acm/app/user/dao/UserDAO.java
  src/main/java/com/acm/app/user/rest/UserController.java
  src/main/java/com/acm/app/user/service/UserService.java
  src/main/java/com/acm/jwt/auth/controller/AuthenticationController.java
  src/main/java/com/acm/jwt/auth/service/AuthenticationService.java
  src/main/java/com/acm/jwt/auth/service/AuthorizationService.java
  src/main/java/com/acm/jwt/config/JwtTokenUtil.java
  src/main/java/com/acm/service/exceptions/InvalidPasswordException.java
  src/main/java/com/acm/service/exceptions/UserNotFoundException.java
  src/main/resources/version.properties
  src/test/java/com/acm/app/user/client/UserClientTest.java
  src/test/java/com/acm/app/user/service/UserServiceTest.java
  src/test/java/com/acm/jwt/auth/controller/AuthenticationControllerTest.java
  src/test/java/com/acm/jwt/auth/service/AuthorizationServiceTest.java
  src/test/java/com/acm/jwt/config/JwtTokenUtilTest.java
Labels: feature

#116 ACMAPP-82: Adding jwtholder class for easy access of token data
  src/main/java/com/acm/jwt/service/JwtHolder.java
  src/test/java/com/acm/jwt/service/JwtHolderTest.java
Labels: Feature

#129 Acmapp 98 create calendar package
  src/main/java/com/acm/app/calendar/client/CalendarClient.java
  src/main/java/com/acm/app/calendar/dao/CalendarDAO.java
  src/main/java/com/acm/app/calendar/mapper/CalendarMapper.java
  src/main/java/com/acm/app/calendar/rest/CalendarController.java
  src/main/java/com/acm/app/calendar/service/CalendarService.java
Labels: Calendar, Feature

#128 ACMAPP: #103 Create Application Package
  src/main/java/com/acm/app/application/client/ApplicationClient.java
  src/main/java/com/acm/app/application/dao/ApplicationDAO.java
  src/main/java/com/acm/app/application/mapper/ApplicationMapper.java
  src/main/java/com/acm/app/application/rest/ApplicationController.java
  src/main/java/com/acm/app/application/service/ApplicationService.java
Labels: Application, Feature

#126 ACMAPP: 97 - Create Github Package Skeleton
  CHANGELOG.md
  src/main/java/com/acm/app/github/client/GithubClient.java
  src/main/java/com/acm/app/github/dao/GithubDAO.java
  src/main/java/com/acm/app/github/mapper/GithubMapper.java
  src/main/java/com/acm/app/github/rest/GithubController.java
  src/main/java/com/acm/app/github/service/GithubService.java
Labels: Feature, GitHub

#137 ACMAPP-131: Adding ability to filter users, and cleaning up code
  CHANGELOG.md
  src/main/java/com/acm/app/mail/client/MailClient.java
  src/main/java/com/acm/app/mail/rest/MailController.java
  src/main/java/com/acm/app/mail/service/MailService.java
  src/main/java/com/acm/app/user/client/UserClient.java
  src/main/java/com/acm/app/user/client/domain/request/UserGetRequest.java
  src/main/java/com/acm/app/user/dao/UserDAO.java
  src/main/java/com/acm/app/user/mapper/UserCredentialMapper.java
  src/main/java/com/acm/app/user/rest/UserController.java
  src/main/java/com/acm/app/user/service/UserService.java
  src/main/java/com/acm/jwt/auth/service/AuthenticationService.java
  src/main/resources/dao/userDAO.acmsql
  src/main/resources/version.properties
  src/test/java/com/acm/app/user/client/UserClientTest.java
  src/test/java/com/acm/app/user/service/UserServiceTest.java
  src/test/java/com/acm/jwt/auth/service/AuthorizationServiceTest.java
Labels: Feature

#142 Task/acmapp0139 clean up mail service
  src/main/java/com/acm/app/mail/rest/MailController.java
  src/main/java/com/acm/app/mail/service/MailService.java
  src/main/java/com/acm/app/user/rest/UserController.java
  src/main/java/com/acm/translations/EmailTranslation.java
  src/main/resources/dao/userDAO.acmsql
Labels: Task

#143 Bug/acmapp 141 annotation update
  src/main/java/com/acm/app/mail/service/MailService.java
  src/main/java/com/acm/app/user/dao/UserDAO.java
  src/main/java/com/acm/app/user/service/UserService.java
  src/main/java/com/acm/jwt/auth/controller/AuthenticationController.java
  src/main/java/com/acm/jwt/auth/service/AuthenticationService.java
  src/main/java/com/acm/jwt/utility/JwtHolder.java
  src/main/java/com/acm/service/activeprofile/ActiveProfile.java
  src/main/java/com/acm/service/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/acm/service/exceptionHandler/domain/ErrorResponse.java
  src/main/java/com/acm/service/sql/SQLBuilder.java
  src/main/java/com/acm/service/sql/SqlClient.java
  src/test/java/com/acm/jwt/utility/JwtHolderTest.java
Labels: Bug

#145 ACMAPP-98: Adding script version to create calendar table
  src/main/resources/db/migration/0.0.0.1__Template.acmsql
  src/main/resources/db/migration/1.0.0.1__Create_AppPermissions_Table.acmsql
  src/main/resources/db/migration/1.0.0.2__Create_Applications_Table.acmsql
  src/main/resources/db/migration/1.0.0.3__Create_GitHub_Table.acmsql
  src/main/resources/db/migration/1.0.0.4__Create_Calendar_Table.acmsql
Labels: Database, Feature

#148 Feature/acmapp 147 create tables for classroom app
  src/main/resources/db/migration/1.0.0.5__Create_Tables_For_Classroom_App.acmsql
Labels: Database, Feature

#151 ACMAPP-150: Cleaning up folder structure and sql files and formatting
  src/main/resources/db/migration/0.0.0.0_SqlScripts
  src/main/resources/db/migration/1.0.0.1__Create_Initial_Table_Setup.sql
  src/main/resources/db/migration/1.0.0.2__Create_Applications_Table.acmsql
  src/main/resources/db/migration/1.0.0.2__Create_Applications_Table.sql
  src/main/resources/db/migration/1.0.0.3__Create_AppPermissions_Table.sql
  src/main/resources/db/migration/1.0.0.4__Create_GitHub_Table.sql
  src/main/resources/db/migration/1.0.0.5__Create_Calendar_Table.sql
  src/main/resources/db/migration/1.0.0.5__Create_Tables_For_Classroom_App.acmsql
  src/main/resources/db/migration/1.0.0.6__Create_Tables_For_Classroom_App.sql
Labels: Database, Task

#153 ACMAPP-149: Creating folder structure for classroom feature
  src/main/java/com/acm/app/classroom/client/ClassroomClient.java
  src/main/java/com/acm/app/classroom/dao/ClassroomDAO.java
  src/main/java/com/acm/app/classroom/mapper/ClassroomMapper.java
  src/main/java/com/acm/app/classroom/rest/ClassroomController.java
  src/main/java/com/acm/app/classroom/service/ClassroomService.java
Labels: Task

#154 ACMAPP-152: Adding create classroom endpoint and cleaning up test files
  src/main/java/com/acm/app/classroom/client/ClassroomClient.java
  src/main/java/com/acm/app/classroom/client/domain/Campus.java
  src/main/java/com/acm/app/classroom/client/domain/Classroom.java
  src/main/java/com/acm/app/classroom/client/domain/Days.java
  src/main/java/com/acm/app/classroom/client/domain/Instructor.java
  src/main/java/com/acm/app/classroom/client/domain/Session.java
  src/main/java/com/acm/app/classroom/dao/ClassroomDAO.java
  src/main/java/com/acm/app/classroom/mapper/ClassroomMapper.java
  src/main/java/com/acm/app/classroom/rest/ClassroomController.java
  src/main/java/com/acm/app/classroom/service/ClassroomService.java
  src/main/java/com/acm/app/user/dao/UserDAO.java
  src/main/java/com/acm/service/sql/SqlClient.java
  src/main/resources/dao/classroomDAO.acmsql
  src/test/java/com/acm/app/classroom/dao/ClassroomDAOTest.java
  src/test/java/com/acm/app/classroom/service/ClassroomServiceTest.java
  src/test/java/com/acm/app/classroom/testData/ClassroomTestFactory.java
  src/test/java/com/acm/app/user/client/UserClientTest.java
  src/test/java/com/acm/app/user/service/UserServiceTest.java
  src/test/java/com/acm/app/user/testData/UserTestFactory.java
Labels: Task
